#!/bin/sh

if ! grep Discharging /sys/class/power_supply/BAT0/status >/dev/null; then
	exit 0
fi

warning_start=20
warning_inc=5
cache_file="${XDG_CACHE_HOME:-~/.cache}/checkbattery-last"

[ ! -f $cache_file ] && echo $((warning_start + warning_inc)) > $cache_file

max=$(cat $cache_file)
now=$(cat /sys/class/power_supply/BAT0/capacity)

if [ $((now + warning_inc)) -le "$max" ]; then
	notify-send -u critical -a 'system health' 'Low battery' "battery is at $now%"
	echo "$now" > $cache_file
fi
