[buildPlans.iosevka]
family = "Iosevka"
spacing = "normal"
serifs = "sans"

[buildPlans.iosevka.variants]
inherits = "ss14"

[buildPlans.iosevka.variants.design]
turn-v = "curly"
capital-d = "more-rounded"
capital-g = "toothless-corner-serifless-hooked"
capital-k = "curly"
capital-r = "curly"
b = "toothless-corner"
d = "toothless-corner"
f = "serifless"
g = "earless-corner"
i = "serifed-flat-tailed"
k = "curly"
p = "earless-corner"
q = "earless-corner-tailed"
t = "flat-hook"
v = "curly"
w = "curly"
x = "curly"
y = "cursive"
lower-lambda = "curly-turn"
zero = "slashed"
three = "twoarcs"
dollar = "open"
brace = "straight"
paren = "large-contour"

[buildPlans.iosevka.ligations]
inherits = "clike"

[buildPlans.iosevka.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka.widths.normal]
shape = 576
menu = 5
css = "normal"

[buildPlans.iosevka-term]
family = "Iosevka Term"
spacing = "term"
serifs = "sans"

[buildPlans.iosevka-term.variants]
inherits = "ss14"

[buildPlans.iosevka-term.variants.design]
turn-v = "curly"
capital-d = "more-rounded"
capital-g = "toothless-corner-serifless-hooked"
capital-k = "curly"
capital-r = "curly"
b = "toothless-corner"
d = "toothless-corner"
f = "serifless"
g = "earless-corner"
i = "serifed-flat-tailed"
k = "curly"
p = "earless-corner"
q = "earless-corner-tailed"
t = "flat-hook"
v = "curly"
w = "curly"
x = "curly"
y = "cursive"
lower-lambda = "curly-turn"
zero = "slashed"
three = "twoarcs"
dollar = "open"
brace = "straight"
paren = "large-contour"

[buildPlans.iosevka-term.ligations]
inherits = "clike"

[buildPlans.iosevka-term.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-term.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-term.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-term.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka-term.widths.normal]
shape = 576
menu = 5
css = "normal"

[buildPlans.iosevka-fixed]
family = "Iosevka Fixed"
spacing = "fixed"
serifs = "sans"

[buildPlans.iosevka-fixed.variants]
inherits = "ss14"

[buildPlans.iosevka-fixed.variants.design]
turn-v = "curly"
capital-d = "more-rounded"
capital-g = "toothless-corner-serifless-hooked"
capital-k = "curly"
capital-r = "curly"
b = "toothless-corner"
d = "toothless-corner"
f = "serifless"
g = "earless-corner"
i = "serifed-flat-tailed"
k = "curly"
p = "earless-corner"
q = "earless-corner-tailed"
t = "flat-hook"
v = "curly"
w = "curly"
x = "curly"
y = "cursive"
lower-lambda = "curly-turn"
zero = "slashed"
three = "twoarcs"
dollar = "open"
brace = "straight"
paren = "large-contour"

[buildPlans.iosevka-fixed.ligations]
inherits = "clike"

[buildPlans.iosevka-fixed.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-fixed.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-fixed.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-fixed.weights.heavy]
shape = 900
menu = 900
css = 900

[buildPlans.iosevka-fixed.widths.normal]
shape = 576
menu = 5
css = "normal"
