[buildPlans.iosevka-kian]
family = "Iosevka"

[buildPlans.iosevka-kian.variants]
# https://github.com/be5invis/Iosevka/tree/dev-v4#stylistic-sets
inherits = "ss14"

[buildPlans.iosevka-kian.variants.design]
# https://github.com/be5invis/Iosevka/tree/dev-v4#configuring-character-variants
# https://github.com/be5invis/Iosevka/raw/dev-v4/images/charvars.png
turn-v = "curly"
capital-d = "more-rounded"
capital-g = "toothless-rounded"
capital-k = "curly"
capital-r = "curly"
b = "toothless-corner"
d = "toothless-corner"
f = "serifless"
g = "earless-corner"
i = "serifed-tailed"
k = "curly"
p = "earless-corner"
q = "earless-corner-tailed"
v = "curly"
w = "curly"
x = "curly"
y = "cursive"
lambda = "curly"
zero = "slashed"
three = "twoarcs"
dollar = "open"

# Override above variants for each slope:
# [buildPlans.iosevka-kian.variants.upright]
# [buildPlans.iosevka-kian.variants.italic]
# [buildPlans.iosevka-kian.variants.oblique]

[buildPlans.iosevka-kian.ligations]
# https://github.com/be5invis/Iosevka/tree/dev-v4#configuring-ligations
# https://github.com/be5invis/Iosevka/tree/dev-v4#ligations
inherits = "clik"
# disables = []
# enables = []





[buildPlans.iosevka-term-kian]
family = "Iosevka Term"
spacing = "term"

[buildPlans.iosevka-term-kian.variants]
# https://github.com/be5invis/Iosevka/tree/dev-v4#stylistic-sets
inherits = "ss14"

[buildPlans.iosevka-term-kian.variants.design]
# https://github.com/be5invis/Iosevka/tree/dev-v4#configuring-character-variants
# https://github.com/be5invis/Iosevka/raw/dev-v4/images/charvars.png
turn-v = "curly"
capital-d = "more-rounded"
capital-g = "toothless-rounded"
capital-k = "curly"
capital-r = "curly"
b = "toothless-corner"
d = "toothless-corner"
f = "serifless"
g = "earless-corner"
i = "serifed-tailed"
k = "curly"
p = "earless-corner"
q = "earless-corner-tailed"
v = "curly"
w = "curly"
x = "curly"
y = "cursive"
lambda = "curly"
zero = "slashed"
three = "twoarcs"
dollar = "open"

# Override above variants for each slope:
# [buildPlans.iosevka-term-kian.variants.upright]
# [buildPlans.iosevka-term-kian.variants.italic]
# [buildPlans.iosevka-term-kian.variants.oblique]

[buildPlans.iosevka-term-kian.ligations]
# https://github.com/be5invis/Iosevka/tree/dev-v4#configuring-ligations
# https://github.com/be5invis/Iosevka/tree/dev-v4#ligations
inherits = "clik"
# disables = []
# enables = []





[buildPlans.iosevka-force-monospace-kian]
family = "Iosevka Force Monospace"
spacing = "force-monospace"

[buildPlans.iosevka-force-monospace-kian.variants]
# https://github.com/be5invis/Iosevka/tree/dev-v4#stylistic-sets
inherits = "ss14"

[buildPlans.iosevka-force-monospace-kian.variants.design]
# https://github.com/be5invis/Iosevka/tree/dev-v4#configuring-character-variants
# https://github.com/be5invis/Iosevka/raw/dev-v4/images/charvars.png
turn-v = "curly"
capital-d = "more-rounded"
capital-g = "toothless-rounded"
capital-k = "curly"
capital-r = "curly"
b = "toothless-corner"
d = "toothless-corner"
f = "serifless"
g = "earless-corner"
i = "serifed-tailed"
k = "curly"
p = "earless-corner"
q = "earless-corner-tailed"
v = "curly"
w = "curly"
x = "curly"
y = "cursive"
lambda = "curly"
zero = "slashed"
three = "twoarcs"
dollar = "open"

# Override above variants for each slope:
# [buildPlans.iosevka-force-monospace-kian.variants.upright]
# [buildPlans.iosevka-force-monospace-kian.variants.italic]
# [buildPlans.iosevka-force-monospace-kian.variants.oblique]

[buildPlans.iosevka-force-monospace-kian.ligations]
# https://github.com/be5invis/Iosevka/tree/dev-v4#configuring-ligations
# https://github.com/be5invis/Iosevka/tree/dev-v4#ligations
inherits = "clik"
# disables = []
# enables = []





[buildPlans.iosevka-fixed-kian]
family = "Iosevka Fixed"
spacing = "fixed"

[buildPlans.iosevka-fixed-kian.variants]
# https://github.com/be5invis/Iosevka/tree/dev-v4#stylistic-sets
inherits = "ss14"

[buildPlans.iosevka-fixed-kian.variants.design]
# https://github.com/be5invis/Iosevka/tree/dev-v4#configuring-character-variants
# https://github.com/be5invis/Iosevka/raw/dev-v4/images/charvars.png
turn-v = "curly"
capital-d = "more-rounded"
capital-g = "toothless-rounded"
capital-k = "curly"
capital-r = "curly"
b = "toothless-corner"
d = "toothless-corner"
f = "serifless"
g = "earless-corner"
i = "serifed-tailed"
k = "curly"
p = "earless-corner"
q = "earless-corner-tailed"
v = "curly"
w = "curly"
x = "curly"
y = "cursive"
lambda = "curly"
zero = "slashed"
three = "twoarcs"
dollar = "open"

# Override above variants for each slope:
# [buildPlans.iosevka-fixed-kian.variants.upright]
# [buildPlans.iosevka-fixed-kian.variants.italic]
# [buildPlans.iosevka-fixed-kian.variants.oblique]

[buildPlans.iosevka-fixed-kian.ligations]
# https://github.com/be5invis/Iosevka/tree/dev-v4#configuring-ligations
# https://github.com/be5invis/Iosevka/tree/dev-v4#ligations
inherits = "clik"
# disables = []
# enables = []
