.\"
.\"
.\"
.\" DOCUMENT SETUP
.\"
.\"
.\"
.R1
no-label-in-reference
accumulate
label "(A.n|Q) ', ' (P|D.y|D)"
.R2
.nr PS 12p
.nr VS 24p
.\"
.\"
.\"
.\" HEADER (page number)
.\"
.\"
.\"
.P1
.ds CH
.ds RH LASTNAME %
.\"
.\"
.\"
.\" HEADER (document info)
.\"
.\"
.\"
.LP
FULL NAME
.br
PROFESSOR NAME
.br
COURSE TITLE
.br
DATE
.\"
.\"
.\"
.\" TITLE
.\"
.\"
.\"
.LP
.DS C
TITLE
.DE
.\"
.\"
.\"
.\" BODY
.\"
.\"
.\"
.PP
BODY
.\"
.\"
.\"
.\" SOURCES SITED
.\"
.\"
.\"
.bp
.[
$LIST$
.]
