#!/bin/sh

if command -v pactl >/dev/null 2>&1; then # PulseAudio
	# Un-mute
	pactl set-sink-mute 0 false
	# Increase volume
	pactl set-sink-volume 0 +5%
else # ALSA
	# Un-mute
	amixer set Master on
	# Increase volume
	amixer set Master 5%+
fi

# Update statusbar
updatestatusbar 1
