#!/bin/sh

case $BUTTON in
	1) setsid sh -c "\"$TERMINAL\" -e neomutt ; updatestatusbar email" ;;
	3) setsid mailsync ;;
esac >/dev/null 2>&1

find ${MAILDIR:-/var/spool/mail/$(id -un)}/*/INBOX/new -type f | wc -l | sed 's/^0$/📪/; /📪/q; s/^/📬 /' | tr -d '\n'
