#!/bin/sh

case $BUTTON in
	1) "$TERMINAL" -e neomutt ;;
	3) setsid mailsync ;;
esac >/dev/null 2>&1

find ${MAILDIR:-/var/spool/mail/$(id -un)}/*/INBOX/new -type f | wc -l | sed 's/^/📬 /; s/^📬 0$//' | tr -d '\n'
