#!/bin/sh

case $BUTTON in
	1) setsid -f $TERMINAL -e sh -c "ipaddr ; pause" ;;
	3) setsid -f $TERMINAL -e sh -c "rfkill list ; pause" ;;
esac

if ! find /sys/class/net/ -mindepth 1 -maxdepth 1 -not -name lo | xargs -rI '%s' cat %s/carrier | grep 1 >/dev/null 2>&1; then
	printf '✈'
	exit
fi

printf '📡'
ip a | sed -n '/[0-9]: [^l][^o]/,$p' | grep -o 'inet \([0-9]\{1,3\}.\)\{3\}[0-9]\{1,3\}' | sed 's/^inet //' | paste -sd '%' | sed 's/%/, /g'
