#!/bin/zsh

# ls aliases
alias ll='ls -lh'
alias la='ls -A'
alias lla='ls -lAh'
alias llA='ls -lah'
alias l='ls -CF1'

# ls aliases with sudo
alias 'sudo  ll'='sudo ls -lh'
alias 'sudo  la'='sudo ls -A'
alias 'sudo lla'='sudo ls -lAh'
alias 'sudo llA'='sudo ls -lah'
alias 'sudo   l'='sudo ls -CF1'

alias -g rm='rm -Iv'
alias -g cp='cp -iv --reflink=auto'
alias -g mv='mv -iv'
alias -g ln='ln -iv'

# Directory creation shortcuts
alias -g mkd='mkdir -pv'
mkcd() {
	mkdir -pv "$@"
	cd "$1" || exit 1
}

# Text editor
alias v="$EDITOR"
alias nv='v'
alias sv='sudo -e'
alias svim='sudo -e'

# Fuzzy search function
se() {
	[ -n "$@" ] \
		&& fopts="$@" \
		|| fopts="~/.local/bin/scripts ~/.config ~/.local/share ~/.local/src ~/.local/opt ~/*"
	f="$(find $fopts -type f 2>/dev/null | fzf --reverse --height=40% -i)"
	[ -z "$f" ] && return 1
	case "$SHELL" in
		*bash) history -s $EDITOR "$(echo "$f" | sed "s|$HOME|~|")" ;;
		*zsh) fc -AI
			  echo $EDITOR "$(echo "$f" | sed "s|$HOME|~|")" >> $HISTFILE
			  fc -R ;;
	esac
	$EDITOR "$f"
}
so() {
	[ -n "$@" ] \
		&& fopts="$@" \
		|| fopts="~/* ~/.local/bin/scripts ~/.config ~/.local/share ~/.local/src ~/.local/opt"
	f="$(find $fopts -type f 2>/dev/null | fzf --reverse --height=40% -i)"
	[ -z "$f" ] && return 1
	case "$SHELL" in
		*bash) history -s $EDITOR "$(echo "$f" | sed "s|$HOME|~|")" ;;
		*zsh) fc -AI
			  echo $EDITOR "$(echo "$f" | sed "s|$HOME|~|")" >> $HISTFILE
			  fc -R ;;
	esac
	xdg-open "$f"
}
sd() {
	[ -n "$@" ] \
		&& fopts="$@" \
		|| fopts="./* ~/* ~/.local/bin/scripts ~/.config ~/.local/share ~/.local/src ~/.local/opt"
	destdir="$(find $fopts -type d 2>/dev/null | fzf --reverse --height=40% -i)"
	[ $? -ne 0 ] && return 1
	cd "$destdir" \
	&& ls
	case "$SHELL" in
		*bash) history -s cd "$destdir" ;;
		*zsh) fc -AI
			  echo cd $destdir >> $HISTFILE
			  fc -R ;;
	esac
}
ser() {
	exe="$(find ~ -type f -perm -u=x 2>/dev/null | fzf --reverse --height=40% -i)"
	case "$SHELL" in
		*bash) history -s "$(echo "$exe" | sed "s|$HOME|~|")" ;;
		*zsh) fc -AI
			  echo "$(echo "$exe" | sed "s|$HOME|~|")" >> $HISTFILE
			  fc -R ;;
	esac
	"$exe"
}
sec() {
	file="$(find "$@" -type f -not -path '*/.*' 2>/dev/null | sed "s|$HOME|~|" | fzf --reverse --height=40% -i | sed "s|~|HOME|")"
	[ -z "$file" ] && return 1
	read '?'"command to run (use %s to insert filename): "
	eval "echo \"$file\" | xargs -d '\n' -I '%s' $(echo "$REPLY" | sed 's/%s/"%s"/g')"
	case "$SHELL" in
		*bash) history -s "$(echo $REPLY | sed "s|%s|\"$file\"|")" ;;
		*zsh) fc -AI
			  echo "$(echo $REPLY | sed "s|%s|\"$file\"|")" >> $HISTFILE
			  fc -R ;;
	esac
}
sech() {
	file="$(find "$@" -type f 2>/dev/null | sed "s|$HOME|~|" | fzf --reverse --height=40% -i | sed "s|~|HOME|")"
	[ -z "$file" ] && return 1
	read -p "command to run (use %s to insert filename): "
	eval "echo \"$file\" | xargs -d '\n' -I '%s' $(echo "$REPLY" | sed 's/%s/"%s"/g')"
	case "$SHELL" in
		*bash) history -s "$(echo $REPLY | sed "s|%s|\"$file\"|")" ;;
		*zsh) fc -AI
			  echo "$(echo $REPLY | sed "s|%s|\"$file\"|")" >> $HISTFILE
			  fc -R ;;
	esac
}
secd() {
	file="$(find "$@" -type d -not -path '*/.*' 2>/dev/null | sed "s|$HOME|~|" | fzf --reverse --height=40% -i | sed "s|~|HOME|")"
	[ -z "$file" ] && return 1
	read -p "command to run (use %s to insert filename): "
	eval "echo \"$file\" | xargs -d '\n' -I '%s' $(echo "$REPLY" | sed 's/%s/"%s"/g')"
	case "$SHELL" in
		*bash) history -s "$(echo $REPLY | sed "s|%s|\"$file\"|")" ;;
		*zsh) fc -AI
			  echo "$(echo $REPLY | sed "s|%s|\"$file\"|")" >> $HISTFILE
			  fc -R ;;
	esac
}
sechd() {
	file="$(find "$@" -type d 2>/dev/null | sed "s|$HOME|~|" | fzf --reverse --height=40% -i | sed "s|~|HOME|")"
	[ -z "$file" ] && return 1
	read -p "command to run (use %s to insert filename): "
	eval "echo \"$file\" | xargs -d '\n' -I '%s' $(echo "$REPLY" | sed 's/%s/"%s"/g')"
	case "$SHELL" in
		*bash) history -s "$(echo $REPLY | sed "s|%s|\"$file\"|")" ;;
		*zsh) fc -AI
			  echo "$(echo $REPLY | sed "s|%s|\"$file\"|")" >> $HISTFILE
			  fc -R ;;
	esac
}

# Transmission BitTorrent client
alias trd='transmission-daemon'

# Arduino CLI
alias acli='arduino-cli'

# Disable unwanted features in some programs:
alias wget='wget --hsts-file=~/.local/share/wget_hsts'

# Use pinfo(1) instead of info(1)
alias info='pinfo'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Shred and remove in one command
secrm() {
	shred "$@"
	rm "$@"
}

# quickly source shell config
alias sorc="source $ZDOTDIR/.zshrc"

alias scim=sc-im

# Map CapsLock to Escape
alias capsesc='setxkbmap -option caps:escape_shifted_capslock'

# quickly create executable scripts
mkscript() {
	for f in "$@"; do
		if ! [ -e "$f" ]; then
			echo '#!/bin/sh' > "$f"
		fi
	done
	chmod +x "$@"
	vim "$@"
}

alias ctime="date +'%A, %d %B %Y at %H:%M'"

# present using SENT
pres() {
	setsid sh -c "sent \"$@\" ; st" &
	exit
}

# set irssi data/config
alias irssi="irssi --config=$HOME/.config/irssi/config --home=$HOME/.local/share/irssi"

# youtube-dl is a long name
alias ytdl='yt-dlp'

# don't glob urls when using curl or youtube-dl
alias curl='noglob curl'
alias yt-dlp='noglob yt-dlp'

# show progress in xz
xzip() {
	in="$1"
	shift
	pv "$in" | xz -z "$@" > "$in.xz"
}

# git(1)
alias g=git

# use sxiv-rifle by default
alias -g sx=sxiv-rifle

# navigation upstream
alias ..='cd ..'
alias ...='cd ../..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# get memory-hungry processes
alias psmem='ps aux | sort -nr -k 4'

# show disk usage
alias dfr='df -h / /home'

alias please='sudo'
alias fuck='sudo'

# use `tput reset` because it's faster
alias reset='tput reset'

# move into directory in ~/.local/opt
lop() {
	cd "$HOME/.local/opt/$1"
	[ -z "$1" ] && ls -A || :
}

# use bsdtar(1) by default
alias tar=bsdtar

# shortcut for xdg-open(1)
alias xo=xdg-open

# don't glob urls when downloading with wl
alias wl='noglob wl'

# notmuch(1)
alias nom=notmuch

# show nb notes using glow
nbglow() {
	nb show --no-color "$1" | glow -p -
}

# dragon-drag-and-drop
alias drag='dragon-drag-and-drop -a -x'

# colored cat using highlight(1)
alias ccat='highlight -Oansi'

# allow mistyping git-status(1)
alias gs='g s'

# Make tmux assume 256-color support
alias tmux='tmux -2'
