#!/bin/sh

## This script will compile various document formats into a PDF with the same basename

[ $# -lt 1 ] && exit 1

file="$(readlink -f "$1")"
ext="${file##*.}"
base="${file%.*}"

[ -n "$2" ] \
	&& out="$2" \
	|| out="$base.pdf"

case "$ext" in
	ms) groff -me -ms -kpt -Tpdf "$file" > "$base.pdf" ;;
	mom) groff -mom -kpt -Tpdf "$file" > "$base.pdf" ;;
esac
