#!/bin/sh

# redirect error output to a log
logfile="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/mailsync.log"
exec 2>"$logfile"

# set verbosity
quiet=0
case $@ in
	*-q*|*--quiet*) quiet=1 ;;
esac

# set home variable
HOME=${HOME:-/home/$(id -un)}

# cache file
cache_file="${XDG_CACHE_HOME:-$HOME/.cache}/mailsync-unread-count"
if [ ! -f "$cache_file" ]; then
	printf 0 > "$cache_file" \
		|| : ${err:='1'}
fi

# /usr/bin/notify-send -a mailsync '📬 syncing mail...'

# recieve new mail with mbsync
/usr/bin/mbsync -a \
	|| : ${err:='1'}

# send outgoing mail using msmtpq
/usr/local/bin/msmtp-runqueue.sh \
	|| : ${err:='1'}

prev="$(cat "$cache_file")"
unread="$(find "${MAILDIR:-/var/spool/mail/$(id -un)}"/*/INBOX/new -type f | wc -l)"
new="$(expr $unread - $prev)"
echo -n "$unread" > "$cache_file"

if [ ${err:=0} -eq 0 ]; then
	if [ $new -gt 0 ]; then
		[ $quiet -eq 0 ] && /usr/bin/notify-send -a 'mailsync' '📬 done syncing mail' "$new new emails"
	fi
else
	[ $quiet -eq 0 ] && /usr/bin/notify-send -a 'mailsync' '📪 failed to sync mail' "see <i>$logfile</i> for details"
	exit 1
fi

$HOME/.scripts/updatestatusbar email
