#!/bin/sh

if [ $# -gt 0 ]; then
	nf="$(echo -n "$1" | sed 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/; s/[][,:(){}\$\&'\'']//g; s/ - /_/g; s/ /-/g; s/-\+/-/g;')"
	mv -nT "$1" "$nf"
	exit
fi

find . -mindepth 1 -type d -exec "$0" {} \;
find . -type f -exec "$0" {} \;

find . -mindepth 1 -type d -empty -delete
